### ISSUE TITLE
[Bug] Forecast days should be positive number and int

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#151]
**Describe the bug**

**1.**
Logger: custom_components.smart_irrigation.localize
Source: custom_components/smart_irrigation/localize.py:31
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) 
First occurred: 08:03:26 (1 occurrences) 
Last logged: 08:03:26

Couldn't load translations language file for ru

**2.**
Logger: homeassistant.config_entries
Source: custom_components/smart_irrigation/store.py:232 
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) 
First occurred: 08:03:26 (1 occurrences) 
Last logged: 08:03:26

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 104, in async_setup_entry
    await store.set_up_factory_defaults()
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/store.py", line 224, in set_up_factory_defaults
    await self.async_factory_default_zones()
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/store.py", line 232, in async_factory_default_zones
    **{ZONE_ID: 0, ZONE_NAME: localize("defaults.default-zone", self.hass.config.language)+" 1", ZONE_SIZE: 50.5, ZONE_THROUGHPUT: 10.1,ZONE_MODULE:0,ZONE_MAPPING:0,ZONE_LEAD_TIME:0}
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**3.**

Logger: frontend.js.latest.202308020
Source: components/system_log/__init__.py:270 
First occurred: 08:00:17 (2 occurrences) 
Last logged: 08:03:55

**:0:0 Script error.**
http://192.168.1.3:8123/frontend_latest/15664-mac7RvTTaE0.js:1:78491 TypeError: null is not an object (evaluating 'this.contentElement.removeEventListener')

**4.**

Logger: homeassistant.config_entries
Source: components/frontend/__init__.py:289 
First occurred: 08:04:25 (1 occurrences) 
Last logged: 08:04:25

**Error setting up entry Smart Irrigation for smart_irrigation**
Traceback (most recent call last):
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 95, in async_setup_entry
    await async_register_panel(hass)
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/panel.py", line 29, in async_register_panel
    await panel_custom.async_register_panel(
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/panel_custom/__init__.py", line 124, in async_register_panel
    frontend.async_register_built_in_panel(
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/frontend/__init__.py", line 289, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel smart_irrigation

**5.**

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:187 
First occurred: 08:04:25 (1 occurrences) 
Last logged: 08:04:25

**Error setting up entry Smart Irrigation for sensor**
Traceback (most recent call last):
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 132, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**6.**
Automatic weather update and modules are not available  in Smart Irrigation dashboard 


**To Reproduce**
Steps to reproduce the behavior:
1. Removed all ver. 1 instances, updated to ver. 2 beta, restarted HA
2. Successfully created new Smart Irrigation integration with defaults, adding OW api key. 
3. New Smart Irrigation dashboard is presented. Added automatic test zone, but no automatic weather update modules are available.

**Comment by jeroenterheerdt** [comment]
Thanks @andreid1303 for trying this! Can you please include the version name that is shown at the top? For your last comment that no calculation modules are available, can you please include a screenshot, thank you.

**Comment by jeroenterheerdt** [comment]
Hi @andreid1303 I added a new release (beta3) that should fix the underlying issue (the first on your list). I am hopeful that at least part of the other issues on your list will go away with that fix. Please install and thanks again!
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.8.0-beta3

**Comment by andreid1303** [comment]
Thank you. Sorry for late reply. I am away from home now and have some problems for connection to HA. Anyway updated to last beta 8:
 - could add PyETO module and change default mapping for custom sensors for ETO calculation. 
 - can't activate Automatic weather data update.
 - HA Dev. Tools don't see any Smart Irrigation entities
 - restarted HA and don't see Smart Irrigation dashboard anymore, integration can't start due to voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['forecast_days']

Here is my smart_irrigation.storage file content:

{
  "version": 2,
  "minor_version": 1,
  "key": "smart_irrigation.storage",
  "data": {
    "config": {
      "calctime": "23:00",
      "units": "metric",
      "use_owm": true,
      "autocalcenabled": true,
      "autoupdateenabled": false,
      "autoupdateschedule": "days",
      "autoupdatefirsttime": "0:00",
      "autoupdateinterval": "24"
    },
    "zones": [
      {
        "id": "1692078679857",
        "name": "test",
        "size": 100.0,
        "throughput": 17.0,
        "state": "automatic",
        "bucket": 0,
        "old_bucket": 0,
        "delta": 0,
        "duration": 0.0,
        "module": "",
        "multiplier": 1.0,
        "explanation": null,
        "mapping": "",
        "lead_time": 0.0
      }
    ],
    "modules": [
      {
        "id": "0",
        "name": "PyETO",
        "description": "Calculate duration based on the FAO56 calculation from the PyETO library.",
        "config": {
          "solrad_behavior": "3",
          "forecast_days": "-5"
        },
        "schema": [
          {
            "type": "boolean",
            "name": "coastal",
            "required": true,
            "default": false
          },
          {
            "type": "select",
            "options": [
              [
                "1",
                "EstimateFromTemp"
              ],
              [
                "2",
                "EstimateFromSunHours"
              ],
              [
                "3",
                "DontEstimate"
              ]
            ],
            "name": "solrad_behavior",
            "required": true,
            "default": "1"
          },
          {
            "type": "integer",
            "name": "forecast_days",
            "required": true,
            "default": 0
          }
        ]
      }
    ],
    "mappings": [
      {
        "id": 0,
        "name": "Default mapping",
        "mappings": {
          "Dewpoint": {
            "source": "sensor",
            "sensorentity": "sensor.outside_dew_point",
            "unit": ""
          },
          "Evapotranspiration": {
            "source": "none",
            "sensorentity": "",
            "unit": ""
          },
          "Humidity": {
            "source": "sensor",
            "sensorentity": "sensor.outside_humidity",
            "unit": ""
          },
          "Maximum Temperature": {
            "source": "sensor",
            "sensorentity": "sensor.outside_temperature",
            "unit": "",
            "aggregate": "maximum"
          },
          "Minimum Temperature": {
            "source": "sensor",
            "sensorentity": "sensor.outside_temperature",
            "unit": "",
            "aggregate": "minimum"
          },
          "Precipitation": {
            "source": "sensor",
            "sensorentity": "sensor.daily_rain",
            "unit": "",
            "aggregate": "last"
          },
          "Pressure": {
            "source": "owm",
            "sensorentity": "",
            "unit": ""
          },
          "Solar Radiation": {
            "source": "sensor",
            "sensorentity": "sensor.solar_radiation",
            "unit": ""
          },
          "Temperature": {
            "source": "sensor",
            "sensorentity": "sensor.outside_temperature",
            "unit": ""
          },
          "Windspeed": {
            "source": "sensor",
            "sensorentity": "sensor.sw_wind_gust",
            "unit": ""
          }
        },
        "data": [
          "[",
          "]"
        ]
      }
    ]
  }
}

**Comment by jeroenterheerdt** [comment]
Thanks did you see any errors when you tried to activate weather data update? not sure what is going on there.
Also, somehow you got -5 in the forecast_days for module with ID 0. Did you enter that value yourself? It should be 0 or a positive number.... that is not being caught by the interface right now, I think. Can you confirm you entered that value yourself?

**Comment by jeroenterheerdt** [comment]
just released beta9 that includes a fix for the conversion error for forecast days.

**Comment by andreid1303** [comment]
Yes, I did changed forecast days clicking up button. Confirm beta 9 fixed this issue. Forecast days = 0 is only allowed.

Note that there is no any error warning when I passing not existing sensor for PyETO. I checked each one manualy.

Still can't set Automatic weather data update. 
Errors calling Update zones service.


Have several error logs but looks like same issue as follow:

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/smart_irrigation/store.py:457 
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) 
First occurred: 08:54:01 (2 occurrences) 
Last logged: 08:56:47

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 779, in handle_calculate_all_zones
    await self._async_calculate_all()
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 365, in _async_calculate_all
    o, s = self.check_mapping_sources(mapping_id = mapping_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 530, in check_mapping_sources
    mapping = self.store.async_get_mapping(mapping_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/store.py", line 457, in async_get_mapping
    res = self.mappings.get(int(mapping_id))
                            ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by andreid1303** [comment]
Can not delete a single zone. 
Deleted my changed "default" mapping and creating new one shows strikethrough OpenWeatherMap option!

**Comment by andreid1303** [comment]
Well, I have deleted the integration, restarted HA and added the integration again. It seems it is working with all defaults without errors. Will try to change settings to my need and report.

**Comment by andreid1303** [comment]
Automatic weather data update: default is every 24 **days**! What is correct for OW?

**Comment by andreid1303** [comment]
When using one of default zone calculation increases bucket by 6,1 that is not correct value I believe. 
After deleting second default zone it is still listed in HA entities.
Creating a new zone leads to error:

Logger: aiohttp.server
Source: custom_components/smart_irrigation/__init__.py:746 
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) 
First occurred: 10:50:32 (2 occurrences) 
Last logged: 11:06:18

Error handling request
Traceback (most recent call last):
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/websockets.py", line 174, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 592, in async_update_zone_config
    await self.async_remove_entity(zone_id)
  File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/__init__.py", line 746, in async_remove_entity
    entity = self.hass.data[const.DOMAIN]["zones"][zone_id]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: '1'

**Comment by jeroenterheerdt** [comment]
> Automatic weather data update: default is every 24 **days**! It seems incorrect but doesn't allow change it, reset to default.

 That should be 24 hours... Thanks for catching that, I think it's the translation stuff that is causing these weird behaviors.

**Comment by jeroenterheerdt** [comment]
> Can not delete a single zone. Deleted my changed "default" mapping and creating new one shows strikethrough OpenWeatherMap option!

 Is this still happening after reinstall?

**Comment by jeroenterheerdt** [comment]
> When using one of default zone calculation increases bucket by 6,1 that is not correct value I believe. After deleting second default zone it is still listed in HA entities. Creating a new zone leads to calculation error:
> 
> Logger: aiohttp.server Source: custom_components/smart_irrigation/**init**.py:746 Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) First occurred: 10:50:32 (2 occurrences) Last logged: 11:06:18
> 
> Error handling request Traceback (most recent call last): File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/websockets.py", line 174, in post await coordinator.async_update_zone_config(zone, data) File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/**init**.py", line 592, in async_update_zone_config await self.async_remove_entity(zone_id) File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/**init**.py", line 746, in async_remove_entity entity = self.hass.data[const.DOMAIN]["zones"][zone_id] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^ KeyError: '1'
> 
> **with default General, Modules and Mapping settings.**
> 
> sensor.default_zone_1 (deleted in dashboard but still in HA): state: 4316 attributes: id: 0 size: 100 throughput: 17 state: automatic unit_of_measurement: s device_class: duration icon: mdi:sprinkler friendly_name: zone6
> 
> sensor.default_zone_2 (deleted in dashboard but still in HA): state: 0 id: 1 size: 100.1 throughput: 20.2 state: automatic unit_of_measurement: s device_class: duration icon: mdi:sprinkler friendly_name: Default zone 2
> 
> sensor.zone4 (new one): state: 0 attributes: id: '1692259543325' size: 200 throughput: 34 state: automatic unit_of_measurement: s device_class: duration icon: mdi:sprinkler friendly_name: zone4
> 
> Note:

Got it

**Comment by jeroenterheerdt** [comment]
Can I please ask you not reuse the same issue over and over again? It makes it really hard to track. For each bug, please make a separate issue. Thanks. I will fix the two things that are remaining here and then close this. Please open other issues for any more bugs you find.

**Comment by jeroenterheerdt** [comment]
> > Automatic weather data update: default is every 24 **days**! It seems incorrect but doesn't allow change it, reset to default.
> 
> That should be 24 hours... Thanks for catching that, I think it's the translation stuff that is causing these weird behaviors.

going to change this to default 1 days, which is the same as 24 hours of course.

**Comment by jeroenterheerdt** [comment]
> > When using one of default zone calculation increases bucket by 6,1 that is not correct value I believe. After deleting second default zone it is still listed in HA entities. Creating a new zone leads to calculation error:
> > Logger: aiohttp.server Source: custom_components/smart_irrigation/**init**.py:746 Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) First occurred: 10:50:32 (2 occurrences) Last logged: 11:06:18
> > Error handling request Traceback (most recent call last): File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/homeassistant/homeassistant/lib/python3.11/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/websockets.py", line 174, in post await coordinator.async_update_zone_config(zone, data) File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/**init**.py", line 592, in async_update_zone_config await self.async_remove_entity(zone_id) File "/var/homeassistant/.homeassistant/custom_components/smart_irrigation/**init**.py", line 746, in async_remove_entity entity = self.hass.data[const.DOMAIN]["zones"][zone_id] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^ KeyError: '1'
> > **with default General, Modules and Mapping settings.**
> > sensor.default_zone_1 (deleted in dashboard but still in HA): state: 4316 attributes: id: 0 size: 100 throughput: 17 state: automatic unit_of_measurement: s device_class: duration icon: mdi:sprinkler friendly_name: zone6
> > sensor.default_zone_2 (deleted in dashboard but still in HA): state: 0 id: 1 size: 100.1 throughput: 20.2 state: automatic unit_of_measurement: s device_class: duration icon: mdi:sprinkler friendly_name: Default zone 2
> > sensor.zone4 (new one): state: 0 attributes: id: '1692259543325' size: 200 throughput: 34 state: automatic unit_of_measurement: s device_class: duration icon: mdi:sprinkler friendly_name: zone4
> > Note:
> 
> Got it

this should be fixed in the next beta as well.

**Comment by andreid1303** [comment]
Fixed.
