### ISSUE TITLE
Lat lon is read from UI config zetting, not from configuration.yaml (if set) 

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#249]
### What happened?

I just noticed that the "Automatic weather data update" doesn't survive a restart of HA. All of my hourly updates stopped after I restarted HA this morning for the 2023.9.1 Core update. So I won't have any hourly data until tonight's calculation is performed. Hopefully there's a way to restart that after a HA restart? First reported in #230 

### How to reproduce

see above

### Which version are you running?

beta

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
@dlindnegm you reported this in #230. I just checked but on my end the auto update / auto calculate settings are restored and the code to track the time update changes is executed. However, since it is a restart, the auto update will only happen after the first update time configured. So if you set the first update time to 23:00 then it will wait until that time again before performing the first update after the restart.
I don't think there is a good solution here other than getting rid of the first update time all together, but that has downsides as well because then there is no way to control when the update happens. Not sure what is the best option here. Ideas?

**Comment by dlindnegm** [comment]
As it exists now, no one is using this integration with just the GUI because you at least need to call a service to reset the buckets after watering.   I don't understand why anyone would want only one update since that dramatically reduces the accuracy of the evapotranspiration calculation.  If  someone wants to control when the update happens they can disable the auto updates and schedule a service call for that via an automation.  So I think you could drop the first update option, and just leave the option to enable/disable automatic updates, and leave the option to update the sensor data every xxx min/hours/days.  If you leave the default for "Automatically update weather data" to "Yes" it will start collecting sensor data as soon as someone installs the integration, so maybe change that default to "No".   Then you can set the auto update (if enabled) to pull sensor data every xxx min/hours/days immediately after HA is restarted.  

In addition to showing the Last calculated timestamp on each zone it would be nice to show the last update time and how many data points have been collected.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/5708c7a6-eaf6-4853-90ee-5ae6e5122e34)

**Comment by jeroenterheerdt** [comment]
> As it exists now, no one is using this integration with just the GUI because you at least need to call a service to reset the buckets after watering. I don't understand why anyone would want only one update since that dramatically reduces the accuracy of the evapotranspiration calculation. If someone wants to control when the update happens they can disable the auto updates and schedule a service call for that via an automation. So I think you could drop the first update option, and just leave the option to enable/disable automatic updates, and leave the option to update the sensor data every xxx min/hours/days. If you leave the default for "Automatically update weather data" to "Yes" it will start collecting sensor data as soon as someone installs the integration, so maybe change that default to "No". Then you can set the auto update (if enabled) to pull sensor data every xxx min/hours/days immediately after HA is restarted.
> 
> In addition to showing the Last calculated timestamp on each zone it would be nice to show the last update time and how many data points have been collected.
> 
> ![image](https://user-images.githubusercontent.com/24968305/266803417-5708c7a6-eaf6-4853-90ee-5ae6e5122e34.png)

thanks, I was actually trying to make the calc update time show on the zone as well in beta13, but of course introduced a big bug. So please stay clear of that for now (I am deleting the release). I will look into the # data points next and need to think a bit more about your other suggestions.

**Comment by dlindnegm** [comment]
Or maybe just a checkbox on the General tab that reads:  "Continue updates after restart".

**Comment by jeroenterheerdt** [comment]
> Or maybe just a checkbox on the General tab that reads: "Continue updates after restart".

yeah... nah. I think we should get rid of the "start at" idea of updates and just tie it to HA restart or when it was configured. I think that makes sense. So basically, if you set it to update every hour, the first update happens when you configure/restart and then every hour.

**Comment by jeroenterheerdt** [comment]
new beta13 now available, the bug has been removed. this also adds the number of data points.

**Comment by dlindnegm** [comment]
I see the Data last updated:, but not seeing anything for data points.  Or does that only show after a calculate?

**Comment by jeroenterheerdt** [comment]
> I see the Data last updated:, but not seeing anything for data points. Or does that only show after a calculate?

I was lazy and did not update the version number so that might have caused confusion with HACS. I will try to push a next version soon, hopefully including the suggestions you made regarding update timing

**Comment by jeroenterheerdt** [comment]
> I see the Data last updated:, but not seeing anything for data points. Or does that only show after a calculate?

just released beta14. It removes auto update first time and introduces a feature we had in v1: auto update delay. This delay is applied immediately and also after restart. You should see data last updated and number of data points on the zone as soon as you have updated the related sensor group.

**Comment by jeroenterheerdt** [comment]
hmmm.. not sure if the behavior is as intended though. It looks like doesn't fire right away but instead waits X delay seconds to then start the counter according to the schedule (1 hour). We're missing the first update that should happen right away after optional X delay seconds..well, something to work on tomorrow maybe. I am wrapping up for tonight :)

**Comment by dlindnegm** [comment]
Fresh install of beta14 is not working as expected.  Performed a manual 'update all zones' followed by a 'calculate all zones'.  No calculation is preformed and the error below is generated.  Something is messed up in the .storage file.  GUI shows 4 data points, but I only see 2 in the .storage file for the OWM sensors and 1 for My Sensors.  There's a stray 'retrieved' entry on line 320.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/smart_irrigation/__init__.py:400
Integration: Smart Irrigation (documentation, issues)
First occurred: 11:08:50 AM (1 occurrences)
Last logged: 11:08:50 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/statistics.py", line 327, in _exact_ratio
    return (x.numerator, x.denominator)
            ^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'numerator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 181, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 743, in async_update_zone_config
    await self._async_calculate_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 454, in _async_calculate_all
    sensor_values = await self.apply_aggregates_to_mapping_data(mapping)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in apply_aggregates_to_mapping_data
    resultdata[key] = statistics.mean(d)
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/statistics.py", line 430, in mean
    T, total, n = _sum(data)
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/statistics.py", line 193, in _sum
    for n, d in map(_exact_ratio, values):
  File "/usr/local/lib/python3.11/statistics.py", line 330, in _exact_ratio
    raise TypeError(msg)
TypeError: can't convert type 'datetime' to numerator/denominator

[smart_irrigation.storage.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12568544/smart_irrigation.storage.txt)

**Comment by jeroenterheerdt** [comment]
> Fresh install of beta14 is not working as expected. Performed a manual 'update all zones' followed by a 'calculate all zones'. No calculation is preformed and the error below is generated. Something is messed up in the .storage file. GUI shows 4 data points, but I only see 2 in the .storage file for the OWM sensors and 1 for My Sensors. There's a stray 'retrieved' entry on line 320.
> 
> This error originated from a custom integration.
> 
> Logger: aiohttp.server Source: custom_components/smart_irrigation/**init**.py:400 Integration: Smart Irrigation (documentation, issues) First occurred: 11:08:50 AM (1 occurrences) Last logged: 11:08:50 AM
> 
> Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.11/statistics.py", line 327, in _exact_ratio return (x.numerator, x.denominator) ^^^^^^^^^^^ AttributeError: 'datetime.datetime' object has no attribute 'numerator'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/websockets.py", line 181, in post await coordinator.async_update_zone_config(zone, data) File "/config/custom_components/smart_irrigation/**init**.py", line 743, in async_update_zone_config await self._async_calculate_all() File "/config/custom_components/smart_irrigation/**init**.py", line 454, in _async_calculate_all sensor_values = await self.apply_aggregates_to_mapping_data(mapping) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/**init**.py", line 400, in apply_aggregates_to_mapping_data resultdata[key] = statistics.mean(d) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/statistics.py", line 430, in mean T, total, n = _sum(data) ^^^^^^^^^^ File "/usr/local/lib/python3.11/statistics.py", line 193, in _sum for n, d in map(_exact_ratio, values): File "/usr/local/lib/python3.11/statistics.py", line 330, in _exact_ratio raise TypeError(msg) TypeError: can't convert type 'datetime' to numerator/denominator
> 
> [smart_irrigation.storage.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12568544/smart_irrigation.storage.txt)

Yeah, just noticed that as well. Tracking in #255. Not sure where the stray came from though

**Comment by jeroenterheerdt** [comment]
> Fresh install of beta14 is not working as expected. Performed a manual 'update all zones' followed by a 'calculate all zones'. No calculation is preformed and the error below is generated. Something is messed up in the .storage file. GUI shows 4 data points, but I only see 2 in the .storage file for the OWM sensors and 1 for My Sensors. There's a stray 'retrieved' entry on line 320.
> 
> This error originated from a custom integration.
> 
> Logger: aiohttp.server Source: custom_components/smart_irrigation/**init**.py:400 Integration: Smart Irrigation (documentation, issues) First occurred: 11:08:50 AM (1 occurrences) Last logged: 11:08:50 AM
> 
> Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.11/statistics.py", line 327, in _exact_ratio return (x.numerator, x.denominator) ^^^^^^^^^^^ AttributeError: 'datetime.datetime' object has no attribute 'numerator'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/websockets.py", line 181, in post await coordinator.async_update_zone_config(zone, data) File "/config/custom_components/smart_irrigation/**init**.py", line 743, in async_update_zone_config await self._async_calculate_all() File "/config/custom_components/smart_irrigation/**init**.py", line 454, in _async_calculate_all sensor_values = await self.apply_aggregates_to_mapping_data(mapping) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/**init**.py", line 400, in apply_aggregates_to_mapping_data resultdata[key] = statistics.mean(d) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/statistics.py", line 430, in mean T, total, n = _sum(data) ^^^^^^^^^^ File "/usr/local/lib/python3.11/statistics.py", line 193, in _sum for n, d in map(_exact_ratio, values): File "/usr/local/lib/python3.11/statistics.py", line 330, in _exact_ratio raise TypeError(msg) TypeError: can't convert type 'datetime' to numerator/denominator
> 
> [smart_irrigation.storage.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12568544/smart_irrigation.storage.txt)

beta15 fixes this issue.

**Comment by dlindnegm** [comment]
No errors with beta15, but based on several quick updates to the weather data I'm still seeing a huge difference between OWM and My Sensors for the calculated bucket size.   It looks like the issue may be with the daily rain calculation.  

My actual daily rain: 0.291 in
OWM: "Precipitation": 7.9
My Sensors: "Precipitation": 0.01145669328

It looks like for OWM you're converting inches to millimeters, but for My Sensors you're treating 0.291 like it's mm and converting that to inches.  

OWM:
            "Windspeed": 1.0172134622284041,
            "Pressure": 1018,
            "Humidity": 92,
            "Temperature": 18.99,
            "Dewpoint": 17.66,
            "Precipitation": 7.9,
            "retrieved": "2023-09-10T23:28:35.456722"

My Sensors:
            "Dewpoint": 19.27777777777778,
            "Humidity": 96.0,
            "Precipitation": 0.01145669328,
            "Pressure": 980.6308162,
            "Solar Radiation": 0.0,
            "Temperature": 20.0,
            "Windspeed": 0.0,
            "retrieved": "2023-09-10T23:28:35.458021"

**Comment by jeroenterheerdt** [comment]
> > > No errors with beta15, but based on several quick updates to the weather data I'm still seeing a huge difference between OWM and My Sensors for the calculated bucket size. It looks like the issue may be with the daily rain calculation.
> > > My actual daily rain: 0.291 in OWM: "Precipitation": 7.9 My Sensors: "Precipitation": 0.01145669328
> > > It looks like for OWM you're converting inches to millimeters, but for My Sensors you're treating 0.291 like it's mm and converting that to inches.
> > > OWM: "Windspeed": 1.0172134622284041, "Pressure": 1018, "Humidity": 92, "Temperature": 18.99, "Dewpoint": 17.66, "Precipitation": 7.9, "retrieved": "2023-09-10T23:28:35.456722"
> > > My Sensors: "Dewpoint": 19.27777777777778, "Humidity": 96.0, "Precipitation": 0.01145669328, "Pressure": 980.6308162, "Solar Radiation": 0.0, "Temperature": 20.0, "Windspeed": 0.0, "retrieved": "2023-09-10T23:28:35.458021"
> > 
> > 
> > That's weird as that conversion should not happen assuming you have set your MySensors source unit correctly which would be inch in your case, right? I just checked and my values are almost equal between sensors and OWM (-1.5 and - 1.6 for the bucket). Can you share a diagnostics file please? I wonder if somehow it got corrupted.

**Comment by dlindnegm** [comment]
Not sure how much you can tell now that my daily precip is zero.  But the buckets are still being calculated with different precip rates.
 

[smart_irrigation.storage.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12577834/smart_irrigation.storage.txt)

[config_entry-smart_irrigation-5e9f88f7c81e335d858fb9d656b06d81.json (2).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12577840/config_entry-smart_irrigation-5e9f88f7c81e335d858fb9d656b06d81.json.2.txt)

**Comment by jeroenterheerdt** [comment]
> 

Precipitation rate is the industry standard name for how much water sprinklers emit per minute. Nothing to do with rain.

Adding the number will be hard as it's dependent on the module. Also, the delta in the storage file is the result of the module so we already have thatn

**Comment by jeroenterheerdt** [comment]
> Not sure how much you can tell now that my daily precip is zero. But the buckets are still being calculated with different precip rates.
> 
> [smart_irrigation.storage.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12577834/smart_irrigation.storage.txt)
> 
> [config_entry-smart_irrigation-5e9f88f7c81e335d858fb9d656b06d81.json (2).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12577840/config_entry-smart_irrigation-5e9f88f7c81e335d858fb9d656b06d81.json.2.txt)

so your `sensor.terrapin_station_daily_rain` provides values in inch right? It should not have been converted since inch is the default unit for total precipitation when `units: imperail` (as is the case in your setup). Maybe there is a bug where this does not get handled correctly, I will investigate. However, I have a very similar set up and don't see the issue, but that might be because I didn't have any precipitation so there is nothing to wrongly convert :)

**Comment by dlindnegm** [comment]
Yes - inches.  But even with current daily rainfall for today at 0.0 for both OWM and my sensor, the bucket size is being calculated differently as shown in the .storage file:
-3.6 for Test Zone 1 (OWM)  
-7.2 for Test Zone 2 (My sensors)

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/bf61c274-67cd-4769-a571-77f4b5b691db)

**Comment by dlindnegm** [comment]
2 zones, 4 manual updates and one calculate.  OWM shows a bucket of -4.3 and My Sensors shows the bucket at -9.4, all with 0.0 actual rain.  All of the sensors look to be within the ballpark of each other with the exception of Dewpoint.  My current dewpoint is 68.7 F (20.38 C).  OWM is reporting dewpoint of 58.33 F (14.63 C).  Could a difference in dewpoint of 10 degrees F cause the bucket size to more than double?

OWM:
          {
            "Windspeed": 1.084529058993519,
            "Pressure": 1019,
            "Humidity": 52,
            "Temperature": 25.17,
            "Dewpoint": 14.63,
            "Precipitation": 0.0,
            "retrieved": "2023-09-11T12:46:09.451199"
          }

My Sensors:
          {
            "Dewpoint": 20.500000000000004,
            "Humidity": 71.0,
            "Precipitation": 0.0,
            "Pressure": 981.6128692999999,
            "Solar Radiation": 58.320864,
            "Temperature": 26.277777777777775,
            "Windspeed": 0.31292800028739304,
            "retrieved": "2023-09-11T12:46:09.455885"
          }

**Comment by jeroenterheerdt** [comment]
maybe, I am not sure. For sure there was a conversion issue with precipitation though (I had the conversion factors wrong). Fixed that bug, will be in next beta. Looking at dewpoint now.

**Comment by jeroenterheerdt** [comment]
Dewpoint conversion checks out. So I guess the answer to your question is: yes, it can have that impact.

**Comment by dlindnegm** [comment]
All of these readings were taken within a few seconds of each other.  Humidity seems off.  My sensor shows 56.0, OWM shows 44, and the OWM API call shows 54.  So where is that 44 coming from?

API Call:
https://api.openweathermap.org/data/3.0/onecall?lat=xx.xxxx&lon=-xx.xxxx&exclude=hourly,daily,minutely,alerts&units=imperial&appid=xxxxxxxxxxxxx

{"lat":xx.xxxx,"lon":-xx.xxxx,"timezone":"America/New_York","timezone_offset":-14400,"current":{"dt":1694457891,"sunrise":1694430987,"sunset":1694476287,"temp":85.03,"feels_like":87.55,"pressure":1020,"humidity":54,"dew_point":66.52,"uvi":6.26,"clouds":75,"visibility":10000,"wind_speed":4,"wind_deg":250,"wind_gust":5.01,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}]}}

From .storage file:
OWM:
          {
            "Windspeed": 1.6454923653694773,
            "Pressure": 1018,
            "Humidity": 44,
            "Temperature": 27.57,
            "Dewpoint": 14.23,
            "Precipitation": 0.0,
            "retrieved": "2023-09-11T14:43:20.813752"
          }

My Sensors:
          {
            "Dewpoint": 19.444444444444443,
            "Humidity": 56.0,
            "Precipitation": 0.0,
            "Pressure": 980.3260411000001,
            "Solar Radiation": 57.58560000000001,
            "Temperature": 29.222222222222218,
            "Windspeed": 0.894080000821123,
            "retrieved": "2023-09-11T14:43:20.815559"
          }

**Comment by jeroenterheerdt** [comment]
> All of these readings were taken within a few seconds of each other. Humidity seems off. My sensor shows 56.0, OWM shows 44, and the OWM API call shows 54. So where is that 44 coming from?
> 
> API Call: https://api.openweathermap.org/data/3.0/onecall?lat=xx.xxxx&lon=-xx.xxxx&exclude=hourly,daily,minutely,alerts&units=imperial&appid=xxxxxxxxxxxxx
> 
> {"lat":xx.xxxx,"lon":-xx.xxxx,"timezone":"America/New_York","timezone_offset":-14400,"current":{"dt":1694457891,"sunrise":1694430987,"sunset":1694476287,"temp":85.03,"feels_like":87.55,"pressure":1020,"humidity":54,"dew_point":66.52,"uvi":6.26,"clouds":75,"visibility":10000,"wind_speed":4,"wind_deg":250,"wind_gust":5.01,"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}]}}
> 
> From .storage file: OWM: { "Windspeed": 1.6454923653694773, "Pressure": 1018, "Humidity": 44, "Temperature": 27.57, "Dewpoint": 14.23, "Precipitation": 0.0, "retrieved": "2023-09-11T14:43:20.813752" }
> 
> My Sensors: { "Dewpoint": 19.444444444444443, "Humidity": 56.0, "Precipitation": 0.0, "Pressure": 980.3260411000001, "Solar Radiation": 57.58560000000001, "Temperature": 29.222222222222218, "Windspeed": 0.894080000821123, "retrieved": "2023-09-11T14:43:20.815559" }

checking if I can reproduce this.

**Comment by jeroenterheerdt** [comment]
can't reproduce: not sure where that 44 comes from. Humidity is never converted as it is always in percentages. I see the same value retrieved from OWM as stored in the storage file.

**Comment by dlindnegm** [comment]
any way to create a debug/verbose beta that shows the actual API call being made? I'll be using my own sensors and not OWM, but for others that do use OWM sensors it would be nice to confirm that the data is accurate.

**Comment by jeroenterheerdt** [comment]
> any way to create a debug/verbose beta that shows the actual API call being made? I'll be using my own sensors and not OWM, but for others that do use OWM sensors it would be nice to confirm that the data is accurate.

I can definitely add that as a debug log. (people would have to enable debug logging to see it to not flood logs files).

**Comment by dlindnegm** [comment]
Beta16 has the debugging that should show the OWM API call?  I'm not seeing it.  I enabled debug logging and performed an update, and this is all I see referencing the integration.  Not sure what the reference to cached OWM data is about.

2023-09-11 18:10:55.316 INFO (MainThread) [custom_components.smart_irrigation] Updating all zones.
2023-09-11 18:10:55.316 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones
2023-09-11 18:10:55.321 INFO (SyncWorker_10) [custom_components.smart_irrigation.OWMClient] Returning cached OWM data

**Comment by dlindnegm** [comment]
I see see a new option in beta16 called Automatic weather data pruning.  Aren't all of the data points automatically removed at every calculation?

**Comment by jeroenterheerdt** [comment]
> I see see a new option in beta16 called Automatic weather data pruning. Aren't all of the data points automatically removed at every calculation?

yes, they are, but ... what if you have this set up: calculate at 23:00, update every hour, 5 minutes after the hour. When at 23:05 you will get another update for that day which should be ignored because it will skew your results (it will have the total precip for that whole day). If we left it there then the next calculate would include that data point. Hence, the need to auto delete data, by default at 23:59. I had this exact problem in my set up so I decided to do something about it. Makes sense?

**Comment by jeroenterheerdt** [comment]
> Beta16 has the debugging that should show the OWM API call? I'm not seeing it. I enabled debug logging and performed an update, and this is all I see referencing the integration. Not sure what the reference to cached OWM data is about.
> 
> 2023-09-11 18:10:55.316 INFO (MainThread) [custom_components.smart_irrigation] Updating all zones. 2023-09-11 18:10:55.316 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones 2023-09-11 18:10:55.321 INFO (SyncWorker_10) [custom_components.smart_irrigation.OWMClient] Returning cached OWM data

Weird, it's right here: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/130f547c26e8613375b8f36fec5a2232ff64df5f/custom_components/smart_irrigation/OWMClient.py#L72C16-L72C18, so it should work. Are you sure you have 'debug' level set?

**Comment by dlindnegm** [comment]
I'm enabling it as shown below, then performing 2 "Update all Zones".  When I disable debug logging it auto-generates the log file (attached).  I still see nothing about the API call in there.  Does it work for you to show the API call?

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/72f51b74-9397-45a1-ab4d-0d28afee2a44)
[home-assistant_smart_irrigation_2023-09-11T23-43-02.048Z.log]
(https://github.com/jeroenterheerdt/HAsmartirrigation/files/12581079/home-assistant_smart_irrigation_2023-09-11T23-43-02.048Z.log)

**Comment by jeroenterheerdt** [comment]
oh I see, it only shows when the API is actually called, you are getting cached data so far as it has not expired yet:
`2023-09-11 19:41:23.463 INFO (SyncWorker_12) [custom_components.smart_irrigation.OWMClient] Returning cached OWM data`

**Comment by dlindnegm** [comment]
Does that mean you need to fix something?  How long before the cached data expires?  Why does it use cached data & what if I had set it to auto update every minute?  What can I do to make sure it isn't using cached data?  So many questions.....

**Comment by dlindnegm** [comment]
Reenabled debug logging and let it sit until the next 30 minute auto update and this is all that's in the log:

2023-09-11 20:28:56.445 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones

So still nothing to show what API call is being made.

**Comment by jeroenterheerdt** [comment]
Hmpf. That is so weird. I am seeing it on my end. Let me investigate

**Comment by jeroenterheerdt** [comment]
> Reenabled debug logging and let it sit until the next 30 minute auto update and this is all that's in the log:
> 
> 2023-09-11 20:28:56.445 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones
> 
> So still nothing to show what API call is being made.

found a bug - should work now.

**Comment by dlindnegm** [comment]
It works now!  
Where are you getting the GPS coordinates to make that API call?  The ones used per the debug logging are not where I am located and are not what I have in my configuration.yaml file.  They are 112 miles away from my actual location.

**Comment by jeroenterheerdt** [comment]
They are read from the HA config. See settings menu, location. Of course of its 112 miles away from you the numbers are not going to be almost identical.

**Comment by jeroenterheerdt** [comment]
> They are read from the HA config. See settings menu, system, general, location. Of course of its 112 miles away from you the numbers are not going to be almost identical. Restart HA and I believe the new location should be applied.

**Comment by dlindnegm** [comment]
Settings, System, General shows the exact location for my Home, and that matches exactly the coordinates I manually have had all along in my Configuration.yaml file for my Home Zone.   And I know all of that is precise because of my automation for arriving and leaving Home.  So I still don't understand where your code is getting it from.  Me thinks you may need to prompt for Lat & Lon coordinates on the General tab if there's an issue with getting the correct ones from HA.

**Comment by dlindnegm** [comment]
Which HA config file are you reading this from?  I can check that directly.  I wonder if there's an issue with having the Home Zone defined in the yaml file as opposed to doing it thru the GUI.

**Comment by jeroenterheerdt** [comment]
> Which HA config file are you reading this from? I can check that directly. I wonder if there's an issue with having the Home Zone defined in the yaml file as opposed to doing it thru the GUI.

It's the HA config object provided to integrations. I doubt there is an issue there. But... Let me double check my code.

**Comment by jeroenterheerdt** [comment]
Here is the call: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/dcffcb1ba72f9194a1e2e9bdb200412cc214d3fc/custom_components/smart_irrigation/__init__.py#L174
As you can see the lat, long is retrieved from HA config object and passed to OWM client constructor.

**Comment by dlindnegm** [comment]
I think that was it - I removed my home zone coordinates from config.yaml and restarted, and now the GUI shows my home zone is at the same location as the OWM API call - 112 miles away?  I'll move it via the GUi and re-test.  This could be an issue for lots of folks that have set their zone manually like this.  I think the main reason was to adjust the zone radius.

**Comment by jeroenterheerdt** [comment]
> I think that was it - I removed my home zone coordinates from config.yaml and restarted, and now the GUI shows my home zone is at the same location as the OWM API call - 112 miles away? I'll move it via the GUi and re-test. This could be an issue for lots of folks that have set their zone manually like this. I think the main reason was to adjust the zone radius.

well, AFAIK setting zone coordinates in `configuration.yaml` has been deprecated for at least a year now. I can see no issues in the code - so if you are still getting the wrong coordinates there is something wrong on the HA level, which, again, I doubt.

**Comment by dlindnegm** [comment]
Still supported I believe: [https://www.home-assistant.io/integrations/zone/](url)

**Comment by jeroenterheerdt** [comment]
> Still supported I believe: [https://www.home-assistant.io/integrations/zone/](url)

OK, but then at least keep them in sync. I have no control over which one HA provides in it's config.

**Comment by dlindnegm** [comment]
Once set via the configuration.yaml it showed correctly in the GUI.  It was only after I removed it from the yaml file and restarted that it showed 112 miles off in the GUI.  Something to keep in mind if people submit bug reports that OWM bucket is drastically different from their sensors.  Glad we finally got to the bottom of this one!

**Comment by jeroenterheerdt** [comment]
Tagging @gatonero to make sure we capture this in the documentation.

**Comment by jeroenterheerdt** [comment]
Also, let's not close this issue just yet, please run this version for a day to confirm it aligns closely now, as is does on my end

**Comment by jeroenterheerdt** [comment]
and... @dlindnegm ? how are the results on your end? It looks fine on my end.

**Comment by dlindnegm** [comment]
Yes - I still see about a 1 inch difference in the bucket sizes, but likely related to slight differences in humidity, temp, etc, and the fact that I'm using a solar radiation sensor.  The debug did show the correct GPS coords being used.  OK to close!

**Comment by jeroenterheerdt** [comment]
interesting, I see about 0.1 inch difference. I guess that is just par for the. I am going to say this is solved now. Thank you so much for your efforts, input, willingness to test and patience. I was able to fix many bugs due to your hard work. I appreciate it!
