### ISSUE TITLE
Calculating Zone not working any more [pyETO: calculate_et_for_day] missing Minimum/Maximum Temperature

### ISSUE THREAD

**Issue by schmeggspert** [jeroenterheerdt/HAsmartirrigation#471]
### What happened?

Zones are not calculated any more. Trying to press update and calculate but there was a log entry created that Minimum/Maximum temperature not available.
I'm using Smart Irrigation with Openweather integration.
I also tried to reinstall/reconfigure Smart Irrigation without any impact.

Version Information:
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.0
Frontend 20240809.0
Smart Irrigation v2024.8.0

### How to reproduce

Pressing update/calculate

### Relevant log output

```shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:262
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 08:33:44 (3 Vorkommnisse)
Zuletzt protokolliert: 08:33:44

[pyETO: calculate_et_for_day] missing Minimum Temperature. If you have continuous updates on this is expected as min temp is not always available.



Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:266
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 08:33:44 (3 Vorkommnisse)
Zuletzt protokolliert: 08:33:44

[pyETO: calculate_et_for_day] missing Maximum Temperature. If you have continuous updates on this is expected as max temp is not always available.
```

### Which version are you running?

v2024.8.0

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "6.6.31-haos-raspi",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 13.0",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "pyscript": {
      "documentation": "https://github.com/custom-components/pyscript",
      "version": "1.6.1",
      "requirements": [
        "croniter==2.0.2",
        "watchdog==2.3.1"
      ]
    },
    "webuntis": {
      "documentation": "https://github.com/JonasJoKuJonas/homeassistant-WebUntis/",
      "version": "v1.1.4",
      "requirements": [
        "webuntis==0.1.22"
      ]
    },
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2024.7.1",
      "requirements": [
        "tinytuya==1.15.1",
        "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
      ]
    },
    "presence_simulation": {
      "documentation": "https://github.com/slashback100/presence_simulation",
      "version": "4.9",
      "requirements": []
    },
    "iaqualinkRobots": {
      "documentation": "https://github.com/galletn/iaqualink/",
      "version": "v0.3.1",
      "requirements": []
    },
    "localtuya": {
      "documentation": "https://github.com/xZetsubou/hass-localtuya/",
      "version": "6.0.0",
      "requirements": []
    },
    "delete": {
      "documentation": "https://github.com/chomupashchuk/delete-file-home-assistant",
      "version": "1.9",
      "requirements": []
    },
    "files": {
      "documentation": "https://github.com/TarheelGrad1998/files",
      "version": "1.5",
      "requirements": []
    },
    "smart_irrigation": {
      "documentation": "https://github.com/jeroenterheerdt/HASmartIrrigation",
      "version": "v2024.8.0",
      "requirements": []
    },
    "alarmo": {
      "documentation": "https://github.com/nielsfaber/alarmo",
      "version": "v1.10.4",
      "requirements": []
    },
    "solcast_solar": {
      "documentation": "https://github.com/BJReplay/ha-solcast-solar",
      "version": "v4.1.3",
      "requirements": [
        "aiohttp>=3.8.5",
        "aiofiles>=24.1.0",
        "datetime>=4.3",
        "isodate>=0.6.1"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "iaqualink": {
      "documentation": "https://www.home-assistant.io/integrations/iaqualink/",
      "version": "1.2.1-exo",
      "requirements": [
        "git+https://github.com/martinfrench92/iaqualink-py.git@zs500#iaqualink==0.5.3"
      ]
    },
    "epex_spot": {
      "documentation": "https://github.com/mampfes/ha_epex_spot",
      "version": "2.3.8",
      "requirements": [
        "beautifulsoup4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "smart_irrigation",
    "name": "Smart Irrigation",
    "codeowners": [
      "jeroenterheerdt"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "panel_custom"
    ],
    "documentation": "https://github.com/jeroenterheerdt/HASmartIrrigation",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/jeroenterheerdt/HASmartIrrigation/issues",
    "requirements": [],
    "version": "v2024.8.0",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.00011762900001599519
    },
    "01J5FEF2Y6CPQ3G70H8V4SHHKW": {
      "wait_import_platforms": -2.31501912600001,
      "config_entry_setup": 2.416037100000011
    }
  },
  "data": {
    "use_weather_service": true,
    "weather_service": "Open Weather Map",
    "weather_service_api_key": "[redacted]",
    "weather_service_api_version": null,
    "store": {
      "config": {
        "calctime": "23:00",
        "units": "metric",
        "use_weather_service": true,
        "weather_service": "Open Weather Map",
        "autocalcenabled": true,
        "autoupdateenabled": true,
        "autoupdateschedule": "hours",
        "autoupdatedelay": "0",
        "autoupdateinterval": "1",
        "autoclearenabled": true,
        "cleardatatime": "23:59",
        "starteventfiredtoday": false,
        "continuousupdates": false
      },
      "mappings": [
        {
          "id": 0,
          "name": "Standard Sensorgruppe",
          "mappings": {
            "Dewpoint": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            },
            "Evapotranspiration": {
              "source": "none",
              "sensorentity": "",
              "unit": ""
            },
            "Humidity": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            },
            "Precipitation": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            },
            "Pressure": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            },
            "Solar Radiation": {
              "source": "none",
              "sensorentity": "",
              "unit": ""
            },
            "Temperature": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            },
            "Windspeed": {
              "source": "weather_service",
              "sensorentity": "",
              "unit": ""
            }
          },
          "data": [],
          "data_last_updated": "2024-08-17T08:33:42.405371"
        }
      ],
      "modules": [
        {
          "id": 0,
          "name": "PyETO",
          "description": "Die Berechnung der Verunstungsrate basiert auf der FAO56-Formel aus der PyETO-Bibliothek.",
          "config": {
            "forecast_days": "3",
            "coastal": false,
            "solrad_behavior": "4"
          },
          "schema": [
            {
              "type": "boolean",
              "name": "coastal",
              "optional": true,
              "default": false
            },
            {
              "type": "select",
              "options": [
                [
                  "1",
                  "EstimateFromTemp"
                ],
                [
                  "2",
                  "EstimateFromSunHours"
                ],
                [
                  "3",
                  "DontEstimate"
                ],
                [
                  "4",
                  "EstimateFromSunHoursAndTemperature"
                ]
              ],
              "name": "solrad_behavior",
              "required": true,
              "default": {
                "__type": "<enum 'SOLRAD_behavior'>",
                "repr": "<SOLRAD_behavior.EstimateFromTemp: '1'>"
              }
            },
            {
              "type": "integer",
              "name": "forecast_days",
              "optional": true,
              "default": 0
            }
          ]
        }
      ],
      "zones": [
        {
          "id": 1,
          "name": "Garten",
          "size": 33.0,
          "throughput": 7.0,
          "state": "automatic",
          "bucket": 1.957504110755438,
          "old_bucket": 1.957504110755438,
          "delta": 0.0,
          "duration": 0,
          "module": 0,
          "multiplier": 1.0,
          "explanation": "Beachte: Diese Beschreibung nutzt '.' als Dezimalzeichen und zeigt gerundete Werte. Das Modul berechnete einen Evapotranspirationsmangel von 0.0. Der alte Vorrat war 2.0.<br/>Der maximale Vorrat ist 50.0.Der neue Vorrat ist [alter_Vorrat]+[Ver\u00e4nderung]=2.0+0.0=2.0.<br/>Wenn der Vorrat >= 0 ist, ist keine Bew\u00e4sserung n\u00f6tig und die Dauer ist gleich 0",
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1800.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-17T08:33:44.520105",
          "last_updated": "2024-08-17T08:33:42.405371",
          "number_of_data_points": 0
        },
        {
          "id": 2,
          "name": "Hochbeet",
          "size": 2.0,
          "throughput": 1.5,
          "state": "automatic",
          "bucket": 1.957504110755438,
          "old_bucket": 1.957504110755438,
          "delta": 0.0,
          "duration": 0,
          "module": 0,
          "multiplier": 1.0,
          "explanation": "Beachte: Diese Beschreibung nutzt '.' als Dezimalzeichen und zeigt gerundete Werte. Das Modul berechnete einen Evapotranspirationsmangel von 0.0. Der alte Vorrat war 2.0.<br/>Der maximale Vorrat ist 50.0.Der neue Vorrat ist [alter_Vorrat]+[Ver\u00e4nderung]=2.0+0.0=2.0.<br/>Wenn der Vorrat >= 0 ist, ist keine Bew\u00e4sserung n\u00f6tig und die Dauer ist gleich 0",
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 1200.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-17T08:33:44.546009",
          "last_updated": "2024-08-17T08:33:42.405371",
          "number_of_data_points": 0
        },
        {
          "id": 3,
          "name": "MicroDrip",
          "size": 0.4,
          "throughput": 0.0667,
          "state": "automatic",
          "bucket": 1.957504110755438,
          "old_bucket": 1.957504110755438,
          "delta": 0.0,
          "duration": 0,
          "module": 0,
          "multiplier": 1.0,
          "explanation": "Beachte: Diese Beschreibung nutzt '.' als Dezimalzeichen und zeigt gerundete Werte. Das Modul berechnete einen Evapotranspirationsmangel von 0.0. Der alte Vorrat war 2.0.<br/>Der maximale Vorrat ist 50.0.Der neue Vorrat ist [alter_Vorrat]+[Ver\u00e4nderung]=2.0+0.0=2.0.<br/>Wenn der Vorrat >= 0 ist, ist keine Bew\u00e4sserung n\u00f6tig und die Dauer ist gleich 0",
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 3600.0,
          "maximum_bucket": 50,
          "last_calculated": "2024-08-17T08:33:44.575073",
          "last_updated": "2024-08-17T08:33:42.405371",
          "number_of_data_points": 0
        }
      ]
    }
  }
}

**Comment by jeroenterheerdt** [comment]
Are you certain you are on 2024.8.0 and not one of the betas? Please clear your browser cache to make sure you have the right version installed.

**Comment by schmeggspert** [comment]
Yes, I’m sure I’ve never installed any beta as well as I cleared my browser history and double checked.

**Comment by jeroenterheerdt** [comment]
OK thanks for letting me know. I think this is an issue I actually fixed in a beta. It's likely because there is just one data point. Try updating multiple times before calculating.

**Comment by schmeggspert** [comment]
Thx for the hint! When I’m updating multiple times the error is not shown up but the duration is not calculated - it keep staying 0

**Comment by ravlar** [comment]
Same issue here. Data is available but calculation is always 0. I'll try to install a beta to see if it is sorted out.

**Comment by ravlar** [comment]
Updated to 2024.8.1-beta8 solves the issue 👍

**Comment by akcasoy** [comment]
I redownload the integration to that beta version, but after HA restart i still see the old version.. 

<img width="244" alt="Bildschirmfoto 2024-08-19 um 23 25 17" src="https://github.com/user-attachments/assets/ddebb385-c1bd-4894-b693-554e5a8cf1ed">

What is wrong here?

**Comment by jeroenterheerdt** [comment]
@akcasoy clear your cache: https://jeroenterheerdt.github.io/HAsmartirrigation/installation-updating.html

**Comment by akcasoy** [comment]
> @akcasoy clear your cache: https://jeroenterheerdt.github.io/HAsmartirrigation/installation-updating.html

didn't help either..

**Comment by jeroenterheerdt** [comment]
> > @akcasoy clear your cache: https://jeroenterheerdt.github.io/HAsmartirrigation/installation-updating.html
> 
> didn't help either..

OK, please post a diag file.

**Comment by schmeggspert** [comment]
> Thx for the hint! When I’m updating multiple times the error is not shown up but the duration is not calculated - it keep 0

I uninstalled and reinstalled 2024.8.0 again - now It is calculating when there is more than one datapoints. 

With the beta version I don’t receive any error log message again.

**Comment by jeroenterheerdt** [comment]
@schmeggspert I strongly suspect a browser cache issue here. Glad it works now.

**Comment by akcasoy** [comment]
It still does not work for me... even after updating to the latest version v2024.8.2.
I am seeing this error in the logs:

2024-08-26 23:31:35.675 ERROR (SyncWorker_19) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 502, in async_sensor_state_changed
    data_last_entry = dict(data_last_entry)
                      ^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 8; 2 is required

**Comment by jeroenterheerdt** [comment]
@akcasoy please post your diag file or storage file

**Comment by akcasoy** [comment]
I have now deleted the integration and installed again.. the problem still exists :/
Here is my diagnostic file.
[config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json](https://github.com/user-attachments/files/16754240/config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json)

**Comment by jlrosssc** [comment]
I'm having the same issue.  It worked up until yesterday then quit.  I looked at my logs and it's showing an error with the Pirateweather pressure value causing an pyETO error.  I tried to manually set a value but it's not taking that either.

2024-08-28 20:22:40.871 ERROR (SyncWorker_3) [homeassistant.core] unable to convert unknown to float. Please check the source sensor is available.
2024-08-28 20:22:40.872 ERROR (SyncWorker_3) [custom_components.daily.sensor] unable to convert to float. Please check the source sensor (Sensor.lightning_lightning_distance) is available.
2024-08-28 20:22:41.287 WARNING (MainThread) [custom_components.smart_irrigation.calcmodules.pyeto] [pyETO: calculate_et_for_day] cannot calculate as some data is missing!
2024-08-28 20:22:41.287 WARNING (MainThread) [custom_components.smart_irrigation.calcmodules.pyeto] [pyETO: calculate_et_for_day] missing Pressure.
2024-08-28 20:22:41.321 WARNING (MainThread) [custom_components.smart_irrigation.calcmodules.pyeto] [pyETO: calculate_et_for_day] cannot calculate as some data is missing!
2024-08-28 20:22:41.321 WARNING (MainThread) [custom_components.smart_irrigation.calcmodules.pyeto] [pyETO: calculate_et_for_day] missing Pressure.
2024-08-28 20:22:41.500 ERROR (SyncWorker_12) [homeassistant.core] unable to convert unknown to float. Please check the source sensor is available.

**Comment by jlrosssc** [comment]
I deleted and reinstalled  v2024.8.2 with no change.  Reinstalled v2024.8.0 with no change.  I deleted the directory and restored from a weekly backup to  v2024.8.0 and it's back working.  I will hold off on upgrading again to  v2024.8.2.

**Comment by akcasoy** [comment]
I will never update this integration on the first new release days..

**Comment by jeroenterheerdt** [comment]
> I deleted and reinstalled v2024.8.2 with no change. Reinstalled v2024.8.0 with no change. I deleted the directory and restored from a weekly backup to v2024.8.0 and it's back working. I will hold off on upgrading again to v2024.8.2.

It would have been very helpful if you had given more info on your config, which versions you had installed (especially beta versions) etc. Glad you got it resolved though.

**Comment by jeroenterheerdt** [comment]
> I have now deleted the integration and installed again.. the problem still exists :/ Here is my diagnostic file. [config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json](https://github.com/user-attachments/files/16754240/config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json)

Did you have a beta version installed before?

**Comment by jlrosssc** [comment]
Unfortunately, although I thought it was corrected, it only worked one time. I am back in the same shape now. Sent from my iPhoneOn Aug 30, 2024, at 11:54 AM, Jeroen ter Heerdt ***@***.***> wrote:﻿

I have now deleted the integration and installed again.. the problem still exists :/ Here is my diagnostic file. config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json

Did you have a beta version installed before?

**Comment by jeroenterheerdt** [comment]
> Unfortunately, although I thought it was corrected, it only worked one time. I am back in the same shape now. Sent from my iPhoneOn Aug 30, 2024, at 11:54 AM, Jeroen ter Heerdt ***@***.***> wrote:﻿ I have now deleted the integration and installed again.. the problem still exists :/ Here is my diagnostic file. config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json Did you have a beta version installed before? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Asking again: did you ever have a beta version installed?

**Comment by jlrosssc** [comment]
I don’t think so. Sent from my iPhoneOn Aug 30, 2024, at 2:23 PM, Jeroen ter Heerdt ***@***.***> wrote:﻿

Unfortunately, although I thought it was corrected, it only worked one time. I am back in the same shape now. Sent from my iPhoneOn Aug 30, 2024, at 11:54 AM, Jeroen ter Heerdt @.> wrote:﻿ I have now deleted the integration and installed again.. the problem still exists :/ Here is my diagnostic file. config_entry-smart_irrigation-01J68AR5AMMW69BK3WJNF8D63A.json Did you have a beta version installed before? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

Asking again: did you ever have a beta version installed?

**Comment by jeroenterheerdt** [comment]
are you still having this issue? I can't reproduce it :(

**Comment by geezerrr** [comment]
I'm on the same situation. 
Let me know how I can assist in solving this issue.

**Comment by jeroenterheerdt** [comment]
first, let's reset your browser cache and try again. I can't reproduce this at all on any of my installations.

**Comment by geezerrr** [comment]
Have tried that it's on multiple platforms like iOS app, chrome, safari, windows and so on. 
It started after one of the updates, as I remember something got broke and you releases some days after a new release. I my case it it ended up with this. I was looking for log files that might shine some light on it. 
Can you point me where to find them?

**Comment by geezerrr** [comment]
Just found the option for debug log...
I've inserted the logging in previous post. 
Looks to me it stopped collecting data on 09-09-2024 and since then something broke.

**Comment by jeroenterheerdt** [comment]
I see a lot of sensors referring to openweathermap in your config which are not shown when you edit sensor groups. Did you use those sensors before? Do they still exist on your system? I am wondering if somehow it got confused ... things like `sensor.openweathermap_dew_point`.
